### ISSUE TITLE
Exception Info: System.AggregateException: One or more errors occurred. The semaphore has been disposed.

### ISSUE THREAD

**Issue by chassq** [microsoft/ApplicationInsights-SnapshotCollector#14] opened 2021-06-21 16:47 UTC
Not sure if this is the correct place but we have been seeing this more and more since April timeframe. Not sure what other info to provide so let me know if there is anything else we can try to add. Or please point us in the right direction if possible.

Thanks!!

<Event> 
<System>
<Provider Name=".NET Runtime"/>
<EventID>1026</EventID>
<Level>1</Level>
<Task>0</Task>
<Keywords>Keywords</Keywords>
<TimeCreated SystemTime="2021-04-05T15:47:20Z"/>
<EventRecordID>277402015</EventRecordID>
<Channel>Application</Channel>
<Computer>RD0003FF2BD0FF</Computer>
<Security/>
</System>
<EventData>
<Data>Application: w3wp.exe CoreCLR Version: 5.0.421.11614 .NET Version: 5.0.4 Description: The process was terminated due to an unhandled exception. Exception Info: System.AggregateException: One or more errors occurred. (The semaphore has been disposed.) ---> System.ObjectDisposedException: The semaphore has been disposed. at System.Threading.SemaphoreSlim.CheckDispose() at System.Threading.SemaphoreSlim.Release(Int32 releaseCount) at System.Threading.SemaphoreSlim.Release() at Microsoft.ApplicationInsights.SnapshotCollector.Pipeline.ProducerConsumerQueue`1.Produce(T workItem) at Microsoft.ApplicationInsights.SnapshotCollector.Uploader.EnqueueRequest(Request request) at Microsoft.ApplicationInsights.SnapshotCollector.Uploader.Shutdown() at System.Threading.CancellationToken.<>c.<.cctor>b__26_0(Object obj) at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s) at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.CancellationTokenSource.CallbackNode.ExecuteCallback() at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException) --- End of inner exception stack trace --- at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException) at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException) at System.Threading.CancellationTokenSource.Cancel() at Microsoft.ApplicationInsights.SnapshotCollector.ApplicationLifetimeManager.Stop() at Microsoft.ApplicationInsights.SnapshotCollector.AssemblyLoadContextLifetimeManager.OnUnloading(Object sender) at System.Runtime.Loader.AssemblyLoadContext.OnProcessExit() at System.AppContext.OnProcessExit() </Data>
</EventData>
</Event>

**Comment by pharring** [comment] 2021-06-21 18:26
Yup, this is a [known issue](https://github.com/microsoft/ApplicationInsights-dotnet/issues/2097) that was fixed in [1.3.7.5](https://docs.microsoft.com/en-us/azure/azure-monitor/app/snapshot-collector-release-notes#1375)
If you're adding the SnapshotCollector via a nuget, please upgrade to that version.
If this is a "codeless" scenario in Azure App Service, we have an update in progress to upgrade everyone to 1.3.7.5.

**Comment by chassq** [comment] 2021-06-21 18:39
Thank you so very much!

**Comment by ptjuanramos** [comment] 2021-06-24 11:16
@pharring  Sorry in opening this issue again, but do you have any estimation in when the update is going to be available in codeless scenarios? Or maybe any link to track this situation? Thank you!

**Comment by pharring** [comment] 2021-06-24 14:55
It's a bit out of my hands. The bits were delivered to Azure App Service "Rapid Update" on June 14th.
I checked on it yesterday and it hadn't hit canary yet so I have pinged my contacts to ask for a status update.

**Comment by pharring** [comment] 2021-06-25 00:38
I got a status update. Unfortunately, we ran into a planned deployment freeze which runs until July 1st. The roll-out is currently scheduled to begin on July 2nd. However, I note that that's a Friday before the US 4th July holiday, so I have a strong suspicion it'll be deferred again by a few days. I'll update this issue as we learn more.

**Comment by ptjuanramos** [comment] 2021-06-25 08:09
Thank you @pharring for the notice! Just a side comment, It would be great to have a kind of a platform to track the versions in Azure btw 😝

**Comment by pharring** [comment] 2021-07-02 18:02
July 2nd roll-out has begun and it includes the updated Snapshot Collector 1.3.7.5. Historically, it has taken about 7 days to finish worldwide deployment, starting in canary regions. The 4th July US holiday may add a day or two to that. Also, there are quite a few other bits riding along with this payload, so the risk of stalls and roll-backs is somewhat higher.

**Comment by ptjuanramos** [comment] 2021-07-19 09:01
@pharring thanks for your information! We will keep awaiting for the deploy :) 
We are still receiving some e-mails about the crash, is there any temporary solution that you know? Thank you and sorry!

**Comment by pharring** [comment] 2021-07-19 16:34
The roll-out was paused for a week because of a regression in an unrelated payload. That was patched and restarted last week. We're currently holding waiting for confirmation that the patch is good. Assuming no further hold-ups, I expect the roll-out to complete this week. I know it's frustrating -- it's frustrating for me too.
The only workaround I can think of is to disable Snapshot Debugging altogether, but that's a bit drastic.

**Comment by daveaglick** [comment] 2021-07-19 19:30
We're seeing the exact same problem with the same call stack in a "codeless" Azure App Service scenario. Thanks for confirming it's in the Azure bits and a rollout is pending, and for keeping us updated. I'll subscribe to this issue and continue to watch for further updates on the rollout.

**Comment by pharring** [comment] 2021-07-22 17:48
The roll-out has completed (Deployed on 99.55% of all App Services worldwide at time of writing). 

To check that you have the latest version, go to the Kudu endpoint "/DiagnosticServices"
e.g. if your site's URL is https://mysite.azurewebsites.net, then go to https://mysite.**scm**.azurewebsites.net**/DiagnosticServices**

You should see something like this at the top:
**Diagnostic Services Status**
Site Extension, version **3.11.2106.1101**, is up to date.
Application Insights Profiler WebJob, version **2.6.2010.2703**, is enabled.
Application Insights Snapshot Collector, version **1.3.7.5**, is installed.

Screenshot below:
![image](https://user-images.githubusercontent.com/9952654/126684490-af36733e-ef73-4583-9fe8-bdba1e13ce03.png)


You may need to restart your site to pick up the latest version -- or just wait, because if you're experiencing this issue then your app has already shut down and it'll pick up the new version next time it starts.

**Comment by pharring** [comment] 2021-07-24 14:36
Sadly, this update caused some apps to fail on start up (FileNotFoundException for System.Text.Encodings.Web). As a rapid mitigation, we are rolling out another update (essentially rolling back to the previous DiagnosticServices site extension). Because that version includes SnapshotCollector 1.3.7.4, that means this issue will re-appear.

Obviously, we'll try and get a fix for the FileNotFoundException _and_ SnapshotCollector 1.3.7.5 deployed safely as soon as we can.

**Comment by pharring** [comment] 2021-08-16 18:41
This should now be fixed (again!) in DiagnosticServices 3.11.2108.201

![image](https://user-images.githubusercontent.com/9952654/129613275-1d11adab-a0ac-4174-9d43-b9625a11a880.png)

**Closed by pharring** 2021-08-16 18:41 UTC
Labels: bug
